const { Mapping } = require('../migrate/models');

/**
 * Build mapping JSON from preset definition and discovered schema
 * @param {Object} definition - preset definition (per JSON schema)
 * @param {Object} schema - { firebird: { tables: { NAME: {...} } }, mysql: { tables: {...} } }
 * @returns {Object} mapping object in wizard format
 */
async function buildMappingFromPreset(definition, schema) {
	if (!definition || !definition.tablePairs) throw new Error('Invalid preset definition');

	const mapping = {
		id: null,
		mappingProfileId: null,
		name: definition.name || `Preset ${definition.code || ''}`,
		tables: {}
	};

	const fbTables = schema?.firebird?.tables || {};
	const myTables = schema?.mysql?.tables || {};

	// helper to fuzzy match columns
	function findTargetCol(targetColsArray, srcColName) {
		const lower = (srcColName || '').toLowerCase();
		let match = targetColsArray.find(tc => tc.name.toLowerCase() === lower);
		if (match) return match.name;
		const fuzzy = lower.replace(/[_\s-]/g, '');
		match = targetColsArray.find(tc => tc.name.toLowerCase().replace(/[_\s-]/g, '') === fuzzy);
		return match ? match.name : null;
	}

	for (const pair of definition.tablePairs || []) {
		const src = String(pair.sourceTable || '').toUpperCase();
		const tgt = String(pair.targetTable || '').toLowerCase();

		// find actual schema entries
		const srcEntry = Object.values(fbTables).find(t => t.name.toUpperCase() === src || t.name === src);
		const tgtEntry = Object.values(myTables).find(t => t.name.toLowerCase() === (tgt.toLowerCase()));

		if (!srcEntry || !tgtEntry) {
			// skip if missing and option says skipMissingTables
			if (definition.options && definition.options.skipMissingTables) {
				console.debug('[Presets] Skipping missing table pair', pair);
				continue;
			}
			// otherwise still include but leave empty
		}

		const sourceName = srcEntry ? srcEntry.name : src;
		const targetName = tgtEntry ? tgtEntry.name : pair.targetTable;

		mapping.tables[sourceName] = mapping.tables[sourceName] || { targetTable: targetName, columns: {}, autoGenerated: true, presetCode: definition.code };

		// Auto-map fields
		if (srcEntry && tgtEntry) {
			const sourceCols = Object.keys(srcEntry.columns || {}).map(n => ({ name: n }));
			const targetCols = Object.keys(tgtEntry.columns || {}).map(n => ({ name: n }));

			sourceCols.forEach(sc => {
				const matched = findTargetCol(targetCols, sc.name);
				if (matched) {
					mapping.tables[sourceName].columns[sc.name] = { targetColumn: matched };
				}
			});
		}
	}

	// Apply forced overrides
	for (const block of definition.forcedFieldMappings || []) {
		const srcTbl = block.sourceTable;
		const srcEntry = Object.values(fbTables).find(t => t.name.toUpperCase() === String(srcTbl).toUpperCase());
		const key = srcEntry ? srcEntry.name : String(srcTbl).toUpperCase();
		if (!mapping.tables[key]) continue;
		const overrides = block.overrides || [];
		overrides.forEach(o => {
			if (!o.sourceField || !o.targetField) return;
			// Map by exact name (case-insensitive)
			const found = Object.keys(mapping.tables[key].columns || {}).find(c => c.toLowerCase() === String(o.sourceField).toLowerCase()) || o.sourceField;
			mapping.tables[key].columns[found] = mapping.tables[key].columns[found] || {};
			mapping.tables[key].columns[found].targetColumn = o.targetField;
		});
	}

	return mapping;
}

module.exports = {
	buildMappingFromPreset
};
